version: "3.7"
services:
  db:
    image: mysql-image
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./api/db/data:/var/lib/mysql

  api:
    build: "./api"
    image: node-image
    container_name: node-container
    restart: always
    volumes: 
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db

  web:
    image: php-image
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - api
